# Generated by Django 5.0.6 on 2024-07-18 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_advertisment_alter_new_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='image',
            field=models.ImageField(blank=True, upload_to='advertisment/image/'),
        ),
        migrations.CreateModel(
            name='AddsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='advertisment/image/')),
                ('adds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.advertisment')),
            ],
        ),
    ]
