# Generated by Django 5.0.6 on 2024-06-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='dicount_amount',
            new_name='discount_amount',
        ),
    ]
