# Generated by Django 5.0.6 on 2024-06-24 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_rename_dicount_amount_coupon_discount_amount'),
        ('shop', '0009_alter_shop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couponshop', to='shop.shop'),
        ),
    ]
