# Generated by Django 5.0.6 on 2024-06-24 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_coupon_shop'),
        ('shop', '0009_alter_shop_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couponshop', to='shop.shop'),
        ),
    ]
