# Generated by Django 5.0.6 on 2024-06-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_update_product_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_sub_catagory',
            field=models.BooleanField(default=False),
        ),
    ]
