# Generated by Django 5.0.6 on 2024-06-21 07:49

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shop_adress_shop_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='adress',
            field=models.CharField(default='bahirdar', max_length=200, validators=[shop.models.validate_no_numbers]),
        ),
    ]
