# Generated by Django 5.0.6 on 2024-07-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_productrecommandation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrecommandation',
            name='purchased_with_times',
            field=models.IntegerField(default=1),
        ),
    ]
