# Generated by Django 5.0.6 on 2024-07-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
