# Generated by Django 5.0.6 on 2024-10-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_shop_logo_alter_product_slug_alter_subcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='adress',
        ),
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(default='bahir dar', max_length=200),
        ),
    ]
