# Generated by Django 5.0.6 on 2024-06-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('out of delivery', 'Out of Delivery'), ('confirmed', 'Order Confirmed')], default='Pending', max_length=30),
        ),
    ]
