# Generated by Django 5.0.6 on 2024-10-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='house_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='house_no'),
        ),
    ]
